### ISSUE TITLE
Expression that evaluates to falsy value will return as null instead

### ISSUE THREAD

**Issue by prndP** [jmespath-community/typescript-jmespath#26]
Hi there. While testing, I noticed a difference in typescript-jmespath behavior vs jmespath.js

 For the following condition, I would expect the result of the expression to be `0`. Today it returns `null`

```
{
   "given":
       {"foo": {"bar": 0}},
   "cases": [
       {
           "expression": "foo.bar",
           "result": 0
       }
   ]
}
```

I could raise a set of PRs which I believe will solve the issue. Thanks

**Comment by springcomp** [comment]
Indeed you are right.
Thanks for the feedback.
A pull request would be awesome, thank you for tour proposal.
