### ISSUE TITLE
Custom functions not visible/available in let expressions

### ISSUE THREAD

**Issue by mikaelforslund** [jmespath-community/typescript-jmespath#29]
Looks like custom functions kept in the functionTable are lost when a new scope is created in TreeInterpreter.ts. 

I can create a PR for a fix if nobody is working on that at the moment?

**Comment by springcomp** [comment]
Hi @mikaelforslund  thanks for your feedback.
If you have a test that exhibits this issue then a PR would be greatly appreciated.
