### ISSUE TITLE
Accessing a zero value using root evaluates to null

### ISSUE THREAD

**Issue by edkim-finch** [jmespath-community/typescript-jmespath#30]
`search({ index: 0 }, '$.index')` returns `null` instead of `0`
`search({ index: 1 }, '$.index')` correctly returns `1`
`search({ index: 0 }, 'index')` correctly returns `0`

**Comment by springcomp** [comment]
This is somehow fixed when compiling the code from the `main` branch.
I’m not sure what could be the difference… 🤔

Will update the package soon anyway to patch vulnerabitilies and include a fix for a separate issue.

**Comment by springcomp** [comment]
FYI, the package is available on [npm](https://www.npmjs.com/package/@jmespath-community/jmespath/v/1.1.4).

**Comment by edkim-finch** [comment]
Thank you!!On Oct 27, 2024, at 12:40 AM, Maxime Labelle ***@***.***> wrote:﻿
FYI, the package is available on npm.
