### ISSUE TITLE
Feature request: upper parent access from the current node

### ISSUE THREAD

**Issue by nguyen-vo** [jmespath-community/typescript-jmespath#34]
As a user, I want to access the parent property to construct a new object that use the parent property and the current node.

For example: Given an object with nested list. I would like to create a new list from the billableItemIds that contain the. In this use case we want to access the invinvoiceLines id when we are looking at the billiableItemIds
```json
{
  "invoiceLines": [
    {
      "id": "1b82af25-ca6a-5057-e063-fa8818ac9479",
      "billableItemIds": [
        "1",
        "2"
      ]
    },
    {
      "id": "ca6aaf25-cc6a-5057-e063-ca50576af25a",
      "billableItemIds": [
        "3",
        "4"
      ]
    }
  ]
}
```

Expected output:
```json
[
  {
    "invoiceLineId":"1b82af25-ca6a-5057-e063-fa8818ac9479",
    "billableItemId": 1
  },
  
  {
    "invoiceLineId":"1b82af25-ca6a-5057-e063-fa8818ac9479",
    "billableItemId": 2
  },
  
  {
    "invoiceLineId":"ca6aaf25-cc6a-5057-e063-ca50576af25a",
    "billableItemId": 3
  },
  
  {
    "invoiceLineId":"ca6aaf25-cc6a-5057-e063-ca50576af25a",
    "billableItemId": 4
  }
]
```

The [JSONPath-plus ](https://www.npmjs.com/package/jsonpath-plus)library has a token that allows to access the parent object from the current node e,g: `$..book[?(@parent.bicycle && @parent.bicycle.color === "red")].category`

**Comment by springcomp** [comment]
There is currently no syntax to get the parent scope at any point during evaluation.
However, there is a way to capture the current scope at any point and use it when needed.
For instance you can achieve your expected output with the following expression :

`` (invoiceLines[].let \$id=id in billableItemIds[*].{invoiceLineId: \$id, billableItemId: @})[] ``

**Comment by nguyen-vo** [comment]
I see thank you! Then I will close the issue. But before I close the issue one last question. Will there be an improvement in the `let` syntax and the documentation?
- I looked at the documentation before opening the issue. The document is not clear on the `let` usage. So it would be helpful if we could have the result of the examples in the document like other examples
- This is just my opinion as it seems having the `let ... in ...` in the middle of the path is not readable. So maybe have additional characters to group the syntax and make it more readable
